import { ClinicTrinityEnvironment } from './environment.model';

export const environment: ClinicTrinityEnvironment = {
  production: true,
  apiUrl: 'http://localhost:8080/trinity/api',
  authUrl: 'http://localhost:8080/trinity/api/auth',
  hostUrl: 'https://parcel-demo.travelpostservices.eu',
  mobileFeatureUrl: 'https://mobiles-apps-features.vercel.app/admin/file',
  context: '/trinity',
  fakePatientId: '12020d5sd00ds-sds1d5158dsd-1d1sd85d12sd-1s1dsdsd',
  adminRoles: ['ADMIN', 'SUPER_ADMIN'],
  dashboardRoles: ['ADMIN', 'SUPER_ADMIN', 'MEDECIN'],
  patientsRoles: ['ADMIN', 'SUPER_ADMIN', 'MEDECIN', 'INFIRMIER', 'URGENTISTE'],
  agendaRoles: [
    'ADMIN',
    'SUPER_ADMIN',
    'MEDECIN',
    'URGENTISTE',
    'INFIRMIER',
    'RECEPTIONNISTE',
  ],
  laboratoireRoles: ['ADMIN', 'SUPER_ADMIN', 'LABORANTIN', 'MEDECIN'],
  pharmacieRoles: ['ADMIN', 'SUPER_ADMIN', 'PHARMACIEN'],
  facturationRoles: ['ADMIN', 'SUPER_ADMIN', 'COMPTABLE'],
  ressourcesHumainesRoles: ['ADMIN', 'SUPER_ADMIN'],
  medecinsRoles: ['MEDECIN'],
  laborantinsRoles: ['LABORANTIN'],
  deviseMonnetaire: 'FCFA',
  insertedIconUrl: '/assets/images/tracking/inserted-step.png',
  stopOverIconUrl: '/assets/images/tracking/room_time_waiting.png',
  startedIconUrl: '/assets/images/tracking/taking-off-plane-step.jpg',
  generatedIconUrl: '/assets/images/tracking/generated-step.png',
  defaultIconUrl: '/assets/images/pd_logo_sm.png',
  authpages: [1, 2, 3],
  spinners: [1, 2],
  progressbars: [1, 2, 3, 4, 5, 6],
};
