application.version=0.0.1

############################################### JAYSCRIPT PROPERTIES ###################################################
jasypt.algorithm=PBEWithHmacSHA512AndAES_256
jasypt.pool-size=4

############################################### REDIS CONFIGURATION ################
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms


#spring.cache.type=simple
#management.health.redis.enabled=false


############################################### HEADERS AUTH_API_KEY ###################################################
custom.session.user=session-user



##################################################### COOKIES & JWT PROPERTIES ###################################################
auth.access.token.cookie.name=access_token
auth.refresh.token.cookie.name=refresh_token

################################################ CAFFEINE PROPERTIES ###################################################
cache.lifetime=90
cache.capacity.max=200

################################################ URL PROPERTIES ###################################################
permit.swagger.paths=/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/swagger-resources/**,/webjars/**

permit.static.resources.paths=/,/index.html,/favicon.ico,/assets/**,/static/**

permit.public.endpoint=/auth/**,/api/auth/**





